# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-ahwr-message-generator:
    build:
      target: development
    image: ffc-ahwr-message-generator-development
    container_name: ffc-ahwr-message-generator-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.cjs:/home/node/jest.config.cjs
      - ./package.json:/home/node/package.json
      - ./jsconfig.json:/home/node/jsconfig.json

  ffc-ahwr-message-generator-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
