services:
  ffc-ahwr-message-generator:
    build:
      context: .
      target: production
    image: ffc-ahwr-message-generator
    container_name: ffc-ahwr-message-generator
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-message-generator-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
