# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-message-generator:
    build:
      target: development
    image: ffc-ahwr-message-generator-development
    container_name: ffc-ahwr-message-generator-development
    depends_on:
      - ffc-ahwr-message-generator-postgres
    environment:
      USE_PRETTY_PRINT: ${USE_PRETTY_PRINT:-true}
    ports:
      - "3008:3000"
      - "9238:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  ffc-ahwr-message-generator-postgres:
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: ffc-ahwr-message-generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: