services:
  ffc-ahwr-message-generator:
    build:
      context: .
      target: production
    image: ffc-ahwr-message-generator
    container_name: ffc-ahwr-message-generator
    depends_on:
      - ffc-ahwr-message-generator-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-message-generator-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      APPLICATION_API_URI: http://host.docker.internal:3001/api
      EVIDENCE_EMAIL_ENABLED: ${EVIDENCE_EMAIL_ENABLED:-false}
      EMAIL_REPLY_TO_ID: ${EMAIL_REPLY_TO_ID:-c3e9149b-9490-4321-808c-72e709d9d814}
      EVIDENCE_REVIEW_TEMPLATE_ID: ${EVIDENCE_REVIEW_TEMPLATE_ID:-be8fd7ee-4bcd-4bde-88a9-d9f238542723}
      EVIDENCE_FOLLOW_UP_TEMPLATE_ID: ${EVIDENCE_FOLLOW_UP_TEMPLATE_ID:-21cc2409-f99a-4a3a-8a39-dd6a75c9b711}
      EVIDENCE_CARBON_COPY_EMAIL_ADDRESS: ${EVIDENCE_CARBON_COPY_EMAIL_ADDRES:-test@test.com}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_GENERATOR_QUEUE_ADDRESS: ${MESSAGE_GENERATOR_QUEUE_ADDRESS:-ffc-ahwr-message-generator}${MESSAGE_QUEUE_SUFFIX}
      SFD_MESSAGE_QUEUE_ADDRESS: ${SFD_MESSAGE_QUEUE_ADDRESS:-ffc-ahwr-sfd-message}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc-ahwr-message-generator
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-message-generator-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      MULTI_HERDS_ENABLED: ${MULTI_HERDS_ENABLED:-true}

  ffc-ahwr-message-generator-postgres:
    image: postgres:16.7-alpine
    environment:
      POSTGRES_DB: ffc-ahwr-message-generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}