# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-ahwr-message-generator:
    build:
      target: development
    image: ffc-ahwr-message-generator-development
    container_name: ffc-ahwr-message-generator-development
    ports:
      - "3008:3000"
      - "9238:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    networks:
      - ffc-ahwr-message-generator

networks:
  ffc-ahwr-message-generator:
    name: ffc-ahwr-message-generator
    driver: bridge
