services:
  ffc-ahwr-message-generator:
    build:
      context: .
      target: production
    image: ffc-ahwr-message-generator
    container_name: ffc-ahwr-message-generator
    depends_on:
      - ffc-ahwr-message-generator-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-message-generator-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_GENERATOR_QUEUE_ADDRESS: ${MESSAGE_GENERATOR_QUEUE_ADDRESS:-ffc-ahwr-message-generator}${MESSAGE_QUEUE_SUFFIX}
      SFD_MESSAGE_QUEUE_ADDRESS: ${SFD_MESSAGE_QUEUE_ADDRESS:-ffc-ahwr-sfd-message}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc-ahwr-message-generator
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-message-generator-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}

  ffc-ahwr-message-generator-postgres:
    image: postgres:16.7-alpine
    environment:
      POSTGRES_DB: ffc-ahwr-message-generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}