apiVersion: v2
description: Generate and send messages to SFD
name: ffc-ahwr-message-generator
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.7.3
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
