# Required values to support CI pipeline

environment: production
name: ffc-ahwr-message-generator
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-message-generator

appInsights:
  connectionString:

labels: {}

containerConfigMap:
  name: ffc-ahwr-message-generator-config-map

containerSecret:
  name: ffc-ahwr-message-generator-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

port: &port 3000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 200Mi
  limitCpu: 200m
  port: *port
  messageQueueHost: namespace.servicebus.windows.net
  messageGeneratorQueueAddress: ffc-ahwr-message-generator
  sfdMessageQueueAddress: ffc-ahwr-sfd-message
  evidenceEmailEnabled: false
  applicationApiUri: https://ffc-ahwr-application.ffc-ahwr-snd2/api

postgresService:
  postgresDb: ffc-ahwr-message-generator
  postgresqlHost: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: *port
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: *port
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

workloadIdentity: true

azureIdentity:
  enabled: true
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
