{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-message-generator.container-secret") -}}
{{- define "ffc-ahwr-message-generator.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ .Values.appInsights.connectionString | quote }}
  {{- end }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUser }}
{{- end -}}
